language: csharp
solution: MoqMatchExtractor.sln
install:
  - nuget restore MoqMatchExtractor.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MoqMatchExtractor.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MoqMatchExtractorTest/bin/Release/MoqMatchExtractorTest.dll
